# Copyright (c) 2021 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

status = [
  # GitHub actions
  "github/linux/debug/fast",
  "github/linux/fetchcontent/fast",
  "github/linux/hip/fast",
  "github/linux/sanitizers/fast",
  "github/macos/debug",

  # CircleCI static checks
  "ci/circleci: check_circular_deps",
  "ci/circleci: check_module_cmakelists",
  "ci/circleci: clang_format",
  "ci/circleci: cmake_format",
  "ci/circleci: inspect",

  # CircleCI build and test
  "ci/circleci: configure_test_combinations",
  "ci/circleci: configure",
  "ci/circleci: core",
  "ci/circleci: tests.examples",
  "ci/circleci: tests.headers",
  "ci/circleci: tests.performance",
  "ci/circleci: tests.regressions",
  "ci/circleci: tests.unit",
  "ci/circleci: tests.unit.algorithms",
  "ci/circleci: tests.unit.container_algorithms",

  # Jenkins
  "jenkins/cscs/clang-13-debug",
  "jenkins/cscs/clang-9-debug",
  "jenkins/cscs/clang-cuda-debug",
  "jenkins/cscs/gcc-11-debug",
  "jenkins/cscs/gcc-10-apex-spack-debug",
  "jenkins/cscs/gcc-9-debug",
  "jenkins/cscs/gcc-cuda-debug",
]
required_approvals = 0
delete_merged_branches = true
use_squash_merge = false
# Three hours to account for queueing delays
timeout_sec = 10800
