# Copyright (c) 2020 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Linux CI (Debug)

on:
  push:
    branches:
      # Development and release branches
      - main
      - release**
      # Bors branches
      - trying
      - staging
  pull_request:

jobs:
  build:
    name: github/linux/debug/fast
    runs-on: ubuntu-latest
    container: stellargroup/build_env:10

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      shell: bash
      run: |
          cmake \
              . \
              -Bbuild \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Debug \
              -DPIKA_WITH_UNITY_BUILD=ON \
              -DPIKA_WITH_MALLOC=system \
              -DPIKA_WITH_EXAMPLES=ON \
              -DPIKA_WITH_TESTS=ON \
              -DPIKA_WITH_TESTS_EXAMPLES=ON \
              -DPIKA_WITH_TESTS_HEADERS=OFF \
              -DPIKA_WITH_TESTS_MAX_THREADS=2 \
              -DPIKA_WITH_CHECK_MODULE_DEPENDENCIES=On
    - name: Build
      shell: bash
      run: |
          cmake --build build --target all
          cmake --build build --target examples
    - name: Test
      shell: bash
      run: |
          cd build
          ctest \
            --timeout 120 \
            --output-on-failure \
            --tests-regex tests.examples
